# Generated by Django 5.2.1 on 2025-05-21 08:58

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_globalfuelprice_fueltransaction_gasstation_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
