# Generated by Django 5.2.1 on 2025-05-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pendingpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingpayment',
            old_name='amount',
            new_name='liters',
        ),
    ]
